spring.application.name=GatawayTec

server.port=${PORT:8080}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Configuração Global de CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[5]=PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# Rota para o serviço de Autenticação
spring.cloud.gateway.routes[0].id=auth-rotes
spring.cloud.gateway.routes[0].uri=lb://authTec
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Rota para o serviço de Usuários
spring.cloud.gateway.routes[1].id=user-rotes
spring.cloud.gateway.routes[1].uri=lb://USERTEC
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/user/**

# Rota para o serviço de Livros
spring.cloud.gateway.routes[2].id=book-rotes
spring.cloud.gateway.routes[2].uri=lb://BOOKTEC
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/book/**, /api/genero/**

# Rota para o serviço de Empréstimos
spring.cloud.gateway.routes[3].id=borrow-rotes
spring.cloud.gateway.routes[3].uri=lb://BORROWTEC
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/emprestimo/**
